name: reproduce
on: workflow_dispatch
jobs:
  ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: sh reproduce.sh
  macos-intel:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: sh reproduce.sh
  macos-arm:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: sh reproduce.sh
